'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Survey

    Partial Public Class Settings

        '''<summary>
        '''plClosingDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plClosingDate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtClosingDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtClosingDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCalendar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCalendar As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''plGraphWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plGraphWidth As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtGraphWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtGraphWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plPersonal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPersonal As Global.System.Web.UI.UserControl

        '''<summary>
        '''rblstPersonal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblstPersonal As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plSurveyResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSurveyResults As Global.System.Web.UI.UserControl

        '''<summary>
        '''rblstSurveyResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblstSurveyResults As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plSurveyResultTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSurveyResultTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSurveyResultsTremplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSurveyResultsTremplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plResultsData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plResultsData As Global.System.Web.UI.UserControl

        '''<summary>
        '''lnkExport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkExport As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''plClearData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plClearData As Global.System.Web.UI.UserControl

        '''<summary>
        '''lnkClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkClear As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
